### ISSUE TITLE
Peculiar does not support incremental search highlighting

### ISSUE THREAD

**Issue by pluma9** [JRasmusBm/vim-peculiar#5]
I've just found this plugin today, it's brilliant.

When manually typing `:g/pattern`, I got great satisfaction from watching the matching text being highlighted. In many cases, it helps me confirm that there's no typo in the pattern. However, this does not happen when I use `PeculiarG`. Is there any chance that `PeculiarG` can support text highlighting?

**Comment by JRasmusBm** [comment]
Happy I could help! 😄

The current implementation of the prompt is non-interactive. Thus I only know what you searched for when you submit.

Maybe one day to the power of lua I could try to build an interactive prompt, but currently I have no plan to do so:

1. Because it would exclude regular vim users 😇
2. Because it is a large refactor and I don't see the person need for the feature at this time.

If you know how to do this and make it performent, I will happily accept PRs 😄

In the meantime I would suggest the following workaround for searches for you really need incremental highlighting:

1. First perform the search the normal v way (either with / or with pressing * or # on a word).
2. Now run PeculiarG/PeculiarV, leaving the search field empty (Peculiar should pick the last search from the search history) 😄

Does this workaround make sense to you?

**Comment by JRasmusBm** [comment]
One potential dream scenario for this later on will be if you could use Lua to display a preview of the result of running the command against the file. 😇

This issue is very close to a `wontfix` because the plugin doesn't need it and it is a lot of work, but I will review PRs if someone submits an attempt 😄

**Comment by andymass** [comment]
One "simple" possibility is instead of taking `input()` for the G mode, just pre-populate the cmdline with `g/\v[cursor]/Peculiar` or (a bit more complex), `g/\v[cursor]` and use CmdlineLeave to get special behavior.  This will allow incsearch to be completely native.

**Comment by JRasmusBm** [comment]
@andymass Great idea, I will experiment with that 😄
